import type { LucideIcon } from 'lucide-react';
import {
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  ArrowUpFromLine,
  Bot,
  Bug,
  ChevronsDown,
  ChevronsUp,
  ClipboardPaste,
  Clock,
  Copy,
  Crosshair,
  Download,
  FileCode,
  FileDiff,
  FileDown,
  FileText,
  FolderGit2,
  FolderOpen,
  FolderPlus,
  GitFork,
  Globe2,
  Image as ImageIcon,
  ListTree,
  PanelRightClose,
  Plus,
  RefreshCw,
  Scissors,
  Send,
  SquareTerminal,
  Trash2,
  Type,
  X,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  copy: Copy,
  'copy-selection': Copy,
  'copy-turn': Copy,
  'copy-markdown': Copy,
  'copy-content': FileText,
  'copy-note': Copy,
  'copy-path': Copy,
  'copy-line': Copy,
  'copy-title': Copy,
  'copy-image': ImageIcon,
  'copy-run': Copy,
  cut: Scissors,
  paste: ClipboardPaste,
  'auto-sort': ArrowUpDown,
  'sort-name': Type,
  'sort-time': Clock,
  'sort-agent': Bot,
  'create-session': Plus,
  'export-pack': FileDown,
  'export-session': FileDown,
  'export-md': FileDown,
  'export-html': FileCode,
  'fork-from-here': GitFork,
  'fork-session': GitFork,
  'jump-bottom': ChevronsDown,
  'jump-top': ChevronsUp,
  'send-composer': Send,
  back: ArrowLeft,
  forward: ArrowRight,
  inspect: Crosshair,
  devtools: Bug,
  'save-image': Download,
  fetch: ArrowDownToLine,
  pull: ArrowDownToLine,
  push: ArrowUpFromLine,
  refresh: RefreshCw,
  'open-folder': FolderOpen,
  files: FolderOpen,
  'new-project': FolderPlus,
  clone: FolderGit2,
  open: FolderOpen,
  delete: Trash2,
  close: X,
  'close-others': Copy,
  'close-right': PanelRightClose,
  'toggle-diffs': ListTree,
  review: FileDiff,
  terminal: SquareTerminal,
  browser: Globe2,
};

export function contextMenuIcon(
  id: string,
  override?: LucideIcon
): LucideIcon | undefined {
  return override ?? ICONS[id];
}

export const CONTEXT_MENU_ICON_CLASS = 'h-3.5 w-3.5 shrink-0';
