-- A capability catalog is valid only for the exact local CLI + ACP pair that
-- produced it. Keep the last successfully verified pair beside the Agent
-- setting so a fresh app process can validate the catalog with SQLite and
-- filesystem reads alone, without spawning an ACP process from a selector.
--
-- The revision fields are opaque, versioned fingerprints generated by the
-- desktop runtime. They contain file metadata, canonical target information,
-- and (when nearby) a package manifest digest; no package contents are stored.
ALTER TABLE agent_setting ADD COLUMN runtime_cli_path TEXT;
ALTER TABLE agent_setting ADD COLUMN runtime_cli_version TEXT;
ALTER TABLE agent_setting ADD COLUMN runtime_cli_revision TEXT;
ALTER TABLE agent_setting ADD COLUMN runtime_acp_path TEXT;
ALTER TABLE agent_setting ADD COLUMN runtime_acp_version TEXT;
ALTER TABLE agent_setting ADD COLUMN runtime_acp_revision TEXT;
