[package]
name = "executors"
version = "0.1.9"
edition = "2024"

[dependencies]
workspace_utils = { path = "../utils", package = "utils" }
api-types = { path = "../api-types" }
git = { path = "../git" }
tokio = { workspace = true }
tokio-util = { version = "0.7", features = ["io", "compat", "rt"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
ts-rs = { workspace = true }
schemars = { workspace = true }
command-group = { workspace = true }
regex = { workspace = true }
json-patch = { workspace = true }
thiserror = { workspace = true }
futures-io = "0.3.31"
futures = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
sqlx = { version = "0.8.6", default-features = false, features = ["derive"] }
shlex = "1.3.0"

[target.'cfg(windows)'.dependencies]
winsplit = "0.1.0"

[features]
default = []
qa-mode = []
