[package]
name = "vibex-mcp"
version = "0.1.9"
edition = "2024"

[[bin]]
name = "vibex-mcp"
path = "src/main.rs"

[dependencies]
delegation-proto = { path = "../delegation-proto" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
