import { useEffect, useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { AlertTriangle, ExternalLink, Trash2 } from 'lucide-react';
import NiceModal, { useModal } from '@ebay/nice-modal-react';
import { useTranslation } from 'react-i18next';
import { defineModal } from '@/lib/modals';
import { crashReportsApi } from '@/lib/api/crashReports';

export type CrashReportDialogProps = {
  reportId: string;
  repository: string | null;
};

/** GitHub new-issue URLs must stay well under browser/URL limits. */
const MAX_ISSUE_BODY_CHARS = 4000;

async function openExternalUrl(url: string): Promise<void> {
  try {
    const { open } = await import('@tauri-apps/plugin-shell');
    await open(url);
  } catch {
    window.open(url, '_blank', 'noopener,noreferrer');
  }
}

function issueTitle(reportId: string, content: string): string {
  const messageIndex = content.indexOf('panic message:');
  if (messageIndex >= 0) {
    const firstLine = content
      .slice(messageIndex + 'panic message:'.length)
      .trimStart()
      .split('\n')[0]
      ?.trim();
    if (firstLine) {
      return `Crash: ${firstLine.slice(0, 120)}`;
    }
  }
  return `Crash report ${reportId}`;
}

function issueBody(content: string): string {
  const truncated =
    content.length > MAX_ISSUE_BODY_CHARS
      ? `${content.slice(0, MAX_ISSUE_BODY_CHARS)}\n… (truncated — full report copied to clipboard)`
      : content;
  return `<!-- Auto-generated by VibeX crash reporting (opt-in). -->\n\n\`\`\`\n${truncated}\n\`\`\`\n`;
}

const CrashReportDialogImpl = NiceModal.create<CrashReportDialogProps>(
  ({ reportId, repository }) => {
    const modal = useModal();
    const { t } = useTranslation(['dialogs', 'common']);
    const [content, setContent] = useState<string | null>(null);
    const [loadError, setLoadError] = useState<string | null>(null);
    const [busy, setBusy] = useState(false);

    useEffect(() => {
      let cancelled = false;
      crashReportsApi
        .read(reportId)
        .then((text) => {
          if (!cancelled) setContent(text);
        })
        .catch((error) => {
          if (!cancelled)
            setLoadError(
              error instanceof Error ? error.message : String(error)
            );
        });
      return () => {
        cancelled = true;
      };
    }, [reportId]);

    const handleSubmitToGithub = async () => {
      if (!content || !repository) return;
      setBusy(true);
      try {
        try {
          await navigator.clipboard.writeText(content);
        } catch {
          // Clipboard access can fail in unfocused webviews; the issue body
          // still carries the (possibly truncated) report.
        }
        const url = `https://github.com/${repository}/issues/new?title=${encodeURIComponent(
          issueTitle(reportId, content)
        )}&body=${encodeURIComponent(issueBody(content))}`;
        await openExternalUrl(url);
      } finally {
        setBusy(false);
      }
    };

    const handleDelete = async () => {
      setBusy(true);
      try {
        await crashReportsApi.delete(reportId);
      } finally {
        setBusy(false);
        modal.resolve();
      }
    };

    return (
      <Dialog
        open={modal.visible}
        onOpenChange={(open) => {
          if (!open) modal.resolve();
        }}
      >
        <DialogContent className="sm:max-w-[640px]">
          <DialogHeader>
            <div className="flex items-center gap-3">
              <AlertTriangle className="h-5 w-5 text-warning" />
              <DialogTitle>{t('crashReport.title')}</DialogTitle>
            </div>
            <DialogDescription className="text-left pt-2">
              {t('crashReport.description')}
            </DialogDescription>
          </DialogHeader>

          <div className="max-h-72 overflow-auto rounded-md border border-border bg-muted/40 p-3">
            <pre className="whitespace-pre-wrap break-words font-mono text-xs text-foreground">
              {loadError
                ? t('crashReport.loadFailed', { error: loadError })
                : (content ?? t('crashReport.loading'))}
            </pre>
          </div>

          <p className="text-xs text-muted-foreground">
            {t('crashReport.privacyNote')}
          </p>

          <DialogFooter className="gap-2">
            <Button
              variant="outline"
              onClick={() => modal.resolve()}
              disabled={busy}
            >
              {t('crashReport.later')}
            </Button>
            <Button
              variant="outline"
              onClick={() => void handleDelete()}
              disabled={busy}
            >
              <Trash2 className="mr-1.5 h-3.5 w-3.5" />
              {t('crashReport.discard')}
            </Button>
            {repository ? (
              <Button
                onClick={() => void handleSubmitToGithub()}
                disabled={busy || !content}
              >
                <ExternalLink className="mr-1.5 h-3.5 w-3.5" />
                {t('crashReport.submitToGithub')}
              </Button>
            ) : null}
          </DialogFooter>
        </DialogContent>
      </Dialog>
    );
  }
);

export const CrashReportDialog = defineModal<CrashReportDialogProps, void>(
  CrashReportDialogImpl
);
