[package]
name = "deployment"
version = "0.1.5"
edition = "2024"

[dependencies]
db = { path = "../db" }
utils = { path = "../utils" }
git = { path = "../git" }
services = { path = "../services" }
executors = { path = "../executors" }
async-trait = { workspace = true } 
thiserror = { workspace = true } 
anyhow = { workspace = true }
tokio = { workspace = true }
sqlx = { version = "0.8.6", default-features = false }
tracing = { workspace = true }
git2 = { workspace = true }
futures = { workspace = true }
axum = { workspace = true }

