[package]
name = "delegation"
version = "0.1.6"
edition = "2024"

[dependencies]
agents = { path = "../agents" }
delegation-proto = { path = "../delegation-proto" }
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
