[package]
name = "git"
version = "0.1.8"
edition = "2024"

[features]
default = []
cloud = []

[dependencies]
chrono = { workspace = true }
dirs = { workspace = true }
git2 = { workspace = true }
serde = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
ts-rs = { workspace = true }
utils = { path = "../utils" }

[dev-dependencies]
tempfile = { workspace = true }
