/* Generated from RegisteredCommand + DomainCommand. Do not hand-edit. */

export const HOST_COMMANDS = [
  'abort_conflicts_workspace',
  'add_project_repository',
  'add_repo_remote',
  'agent_auth_mode',
  'agent_auth_mode_set',
  'agent_cancel_prompt',
  'agent_capability_catalog',
  'agent_capability_catalog_fresh',
  'agent_connect',
  'agent_connection_snapshot',
  'agent_delete_remote_session',
  'agent_discard_prepared_session',
  'agent_disconnect',
  'agent_import_local_history',
  'agent_import_local_history_batch',
  'agent_import_remote_session',
  'agent_list_live_terminals',
  'agent_list_local_history',
  'agent_list_remote_sessions',
  'agent_list_session_commands',
  'agent_load_session',
  'agent_local_history_import_snapshot',
  'agent_management_account_flow',
  'agent_management_actions',
  'agent_management_apply_update',
  'agent_management_bar',
  'agent_management_cancel_operation',
  'agent_management_check_update',
  'agent_management_clear_diagnostics',
  'agent_management_config_file_write',
  'agent_management_config_read',
  'agent_management_config_write',
  'agent_management_detail',
  'agent_management_diagnostics',
  'agent_management_discovery_progress',
  'agent_management_environment',
  'agent_management_environment_diagnostics',
  'agent_management_environment_write',
  'agent_management_install_version',
  'agent_management_mark_diagnostics_read',
  'agent_management_preflight',
  'agent_management_refresh',
  'agent_management_remove',
  'agent_management_reorder',
  'agent_management_repair',
  'agent_management_rollback',
  'agent_management_run_action',
  'agent_management_set_enabled',
  'agent_management_uninstall',
  'agent_model_provider_bind',
  'agent_model_provider_catalog',
  'agent_model_provider_delete',
  'agent_model_provider_import',
  'agent_model_provider_import_preview',
  'agent_model_provider_probe',
  'agent_model_provider_save',
  'agent_model_providers',
  'agent_new_session',
  'agent_plan_usage',
  'agent_prepare_session',
  'agent_refresh_capability_catalog',
  'agent_registry_add_and_install',
  'agent_registry_refresh',
  'agent_registry_view',
  'agent_reset_to_checkpoint',
  'agent_respond_permission',
  'agent_resume_session',
  'agent_runtime_snapshot',
  'agent_scan_local_history',
  'agent_send_prompt',
  'agent_session_defaults',
  'agent_set_prepared_session_config',
  'agent_set_prepared_session_mode',
  'agent_set_session_defaults',
  'agent_terminal_snapshot',
  'agent_user_definition_add_and_install',
  'agent_user_definition_detail',
  'agent_user_definition_update',
  'apply_workspace_stash',
  'artifact_close_preview',
  'artifact_list',
  'artifact_open_preview',
  'attach_terminal',
  'attach_workspace_pr',
  'attention_inbox_list',
  'automation_cancel_run',
  'automation_create',
  'automation_create_workflow',
  'automation_delete',
  'automation_engine_status',
  'automation_export_spec',
  'automation_import_spec',
  'automation_list',
  'automation_mark_seen',
  'automation_preview_next_runs',
  'automation_run_now',
  'automation_runs',
  'automation_set_enabled',
  'automation_templates',
  'automation_unseen_failures',
  'automation_update',
  'automation_update_workflow',
  'change_workspace_target_branch',
  'check_app_release',
  'check_editor_availability',
  'check_git_repo_path',
  'checkout_repo_branch',
  'checkout_workspace_branch',
  'clear_local_app_data',
  'clone_repo',
  'close_terminal',
  'codex_model_catalog',
  'codex_model_catalog_apply',
  'codex_model_catalog_config',
  'codex_poll_device_code',
  'codex_request_device_code',
  'commit_repo_changes',
  'commit_workspace_changes',
  'connect_chat_channel',
  'continue_conflicts_workspace',
  'continue_rebase_workspace',
  'conversation_archive',
  'conversation_attach',
  'conversation_cancel_turn',
  'conversation_catalog',
  'conversation_checkpoint_file_changes_preview',
  'conversation_child_create',
  'conversation_close',
  'conversation_create',
  'conversation_delete',
  'conversation_detail',
  'conversation_ensure_session_controls',
  'conversation_events_since',
  'conversation_export',
  'conversation_export_html',
  'conversation_export_markdown',
  'conversation_fork',
  'conversation_import',
  'conversation_input_cancel',
  'conversation_input_list',
  'conversation_input_reorder',
  'conversation_input_submit',
  'conversation_input_update',
  'conversation_list',
  'conversation_list_feedback',
  'conversation_list_recent',
  'conversation_output',
  'conversation_rebind_session',
  'conversation_relation_list',
  'conversation_rename',
  'conversation_respond_permission',
  'conversation_respond_question',
  'conversation_search',
  'conversation_set_pinned',
  'conversation_set_session_config_option',
  'conversation_set_session_mode',
  'conversation_set_status',
  'conversation_slash_commands',
  'conversation_start_turn',
  'conversation_steer',
  'conversation_submit_feedback',
  'conversation_timeline_page',
  'conversation_truncate_to_turn',
  'conversation_workspace_create',
  'conversation_workspace_entries',
  'copy_item',
  'crash_report_delete',
  'crash_report_read',
  'crash_reports_list',
  'create_chat_channel',
  'create_directory',
  'create_instruction',
  'create_project',
  'create_project_root_session',
  'create_project_session',
  'create_repo_branch',
  'create_scratch',
  'create_session',
  'create_tag',
  'create_task',
  'create_task_and_start',
  'create_terminal',
  'create_workflow_debug_workspace',
  'create_workspace',
  'create_workspace_branch',
  'create_workspace_from_pr',
  'create_workspace_pr',
  'cursor_model_catalog',
  'delegation_cancel',
  'delete_agent_skill',
  'delete_chat_channel',
  'delete_chat_channel_token',
  'delete_file',
  'delete_image',
  'delete_instruction',
  'delete_project',
  'delete_project_repository',
  'delete_repo_branch',
  'delete_scratch',
  'delete_session',
  'delete_tag',
  'delete_task',
  'delete_workspace',
  'delete_workspace_branch',
  'detect_git_version',
  'disconnect_chat_channel',
  'drop_workspace_stash',
  'dsh_plugin_add',
  'dsh_plugin_remove',
  'dsh_plugins',
  'dsh_provider_delete',
  'dsh_provider_discover_models',
  'dsh_provider_save',
  'dsh_providers',
  'enhance_prompt',
  'ensure_project_workspace',
  'fetch_repo',
  'fetch_workspace',
  'get_chat_channel_has_token',
  'get_chat_command_prefix',
  'get_chat_event_filter',
  'get_chat_event_webhooks',
  'get_chat_include_prompt_text',
  'get_chat_message_language',
  'get_claude_settings',
  'get_claude_settings_path',
  'get_execution_process',
  'get_execution_process_repo_states',
  'get_file_at_head',
  'get_file_tree',
  'get_first_user_message',
  'get_frontend_preferences',
  'get_github_cli_status',
  'get_log_settings',
  'get_logs_dir',
  'get_market_skill_detail',
  'get_profiles',
  'get_project',
  'get_project_repositories',
  'get_project_usage_statistics',
  'get_project_workspaces',
  'get_project_worktree_settings',
  'get_projects',
  'get_recent_logs',
  'get_recent_repos',
  'get_repo',
  'get_repo_branches',
  'get_repo_commit_detail',
  'get_repo_commit_diffs',
  'get_repo_file_diffs',
  'get_repo_git_log',
  'get_repo_git_status',
  'get_repo_remotes',
  'get_repos',
  'get_repos_batch',
  'get_scratch',
  'get_session',
  'get_session_summaries',
  'get_sessions',
  'get_settings_file_path',
  'get_system_proxy_settings',
  'get_system_rendering_settings',
  'get_tags',
  'get_task',
  'get_task_image_metadata',
  'get_task_images',
  'get_user_system_info',
  'get_version_control_settings',
  'get_workspace',
  'get_workspace_branch_status',
  'get_workspace_children',
  'get_workspace_commit_detail',
  'get_workspace_commit_diffs',
  'get_workspace_commit_graph',
  'get_workspace_commit_history',
  'get_workspace_conflict_file',
  'get_workspace_count',
  'get_workspace_file_diffs',
  'get_workspace_git_log',
  'get_workspace_git_status',
  'get_workspace_image_metadata',
  'get_workspace_pr_comments',
  'get_workspace_repos',
  'get_workspaces',
  'get_worktree_cleanup_status',
  'gh_cli_setup',
  'git_cherry_pick',
  'git_create_branch_at_commit',
  'git_reset_to_commit',
  'git_revert_commit',
  'grok_plugin_add',
  'grok_plugin_remove',
  'grok_plugins',
  'init_repo',
  'init_repo_at_path',
  'install_github_cli',
  'install_market_skill',
  'install_official_instruction',
  'install_version_control_tools',
  'kimi_model_catalog',
  'list_agent_skills',
  'list_chat_channel_message_logs',
  'list_chat_channel_statuses',
  'list_chat_channels',
  'list_directory',
  'list_directory_children',
  'list_git_repos',
  'list_instructions',
  'list_official_instructions',
  'list_open_prs',
  'list_prompt_enhancement_models',
  'list_repo_issues',
  'list_workspace_stashes',
  'logout_github_cli',
  'mark_session_viewed',
  'mark_workspace_seen',
  'mcp_get_marketplace_server_detail',
  'mcp_install_marketplace_server',
  'mcp_list_marketplaces',
  'mcp_scan_local',
  'mcp_search_marketplace',
  'mcp_uninstall_server',
  'mcp_upsert_local_server',
  'merge_workspace',
  'move_item',
  'open_github_cli_login',
  'opencode_plugin_add',
  'opencode_plugin_install',
  'opencode_plugin_list',
  'opencode_plugin_uninstall',
  'opencode_provider_catalog',
  'opencode_provider_connect',
  'opencode_provider_connections',
  'opencode_provider_disconnect',
  'opencode_provider_import',
  'opencode_provider_set_enabled',
  'pi_command_validate',
  'pi_configuration',
  'pi_credentials_save',
  'pi_plugin_add',
  'pi_plugin_remove',
  'pi_plugins',
  'pi_runtime_save',
  'play_notification_sound',
  'plugin_action_catalog',
  'plugin_check_updates',
  'plugin_close_file_preview',
  'plugin_contribution_catalog',
  'plugin_control_catalog',
  'plugin_control_configure_agents',
  'plugin_control_configure_mcp',
  'plugin_control_contributions',
  'plugin_control_gc_runtimes',
  'plugin_control_grant_permissions',
  'plugin_control_import',
  'plugin_control_install_runtime',
  'plugin_control_logs',
  'plugin_control_preview_import',
  'plugin_control_rollback',
  'plugin_control_set_enabled',
  'plugin_control_uninstall',
  'plugin_control_update',
  'plugin_install',
  'plugin_invoke_contribution',
  'plugin_marketplace_catalog',
  'plugin_marketplace_index',
  'plugin_marketplace_install',
  'plugin_marketplace_listing',
  'plugin_open_file_preview',
  'plugin_product_detail',
  'plugin_renew_file_preview',
  'plugin_resolve_file_opener',
  'plugin_save_config',
  'plugin_surface_invoke',
  'plugin_surface_open',
  'plugin_surface_revoke',
  'plugin_uninstall',
  'plugin_update',
  'plugin_workflow_catalog',
  'pop_workspace_stash',
  'pull_repo',
  'pull_workspace_branch',
  'push_repo',
  'push_workspace_branch',
  'read_agent_skill',
  'read_binary_asset',
  'read_file_content',
  'read_file_with_truncation',
  'read_local_skill',
  'rebase_back_workspace',
  'rebase_workspace',
  'refresh_prompt_enhancement_catalogs',
  'register_repo',
  'remove_repo_remote',
  'rename_session',
  'rename_workspace_branch',
  'reset_session_process',
  'resize_terminal',
  'respond_to_approval',
  'revert_repo_all',
  'revert_repo_file',
  'revert_workspace_all',
  'revert_workspace_file',
  'run_archive_script',
  'run_cleanup_script',
  'run_setup_script',
  'save_agent_skill',
  'save_chat_channel_token',
  'save_file_content',
  'scan_local_skills',
  'search_project_files',
  'search_repo',
  'search_skill_market',
  'search_workspace_text',
  'set_chat_command_prefix',
  'set_chat_event_filter',
  'set_chat_event_webhooks',
  'set_chat_include_prompt_text',
  'set_chat_message_language',
  'set_log_settings',
  'set_repo_remote_url',
  'set_session_pinned',
  'set_skill_hosting',
  'show_workspace_stash',
  'stage_repo_all',
  'stage_repo_file',
  'stage_workspace_all',
  'stage_workspace_file',
  'start_workspace_dev_server',
  'stash_workspace',
  'stop_execution_process',
  'stop_workspace_execution',
  'subscribe_conversation_stream',
  'subscribe_diff_stream',
  'subscribe_execution_processes_stream',
  'subscribe_file_tree_stream',
  'subscribe_log_stream',
  'subscribe_project_workspaces_stream',
  'subscribe_projects_stream',
  'subscribe_scratch_stream',
  'subscribe_slash_commands_stream',
  'test_chat_channel',
  'test_git_path',
  'trash_item',
  'uninstall_skill',
  'unstage_repo_file',
  'unstage_workspace_file',
  'update_chat_channel',
  'update_claude_settings',
  'update_config',
  'update_frontend_preferences',
  'update_instruction',
  'update_profiles',
  'update_project',
  'update_project_worktree_settings',
  'update_repo',
  'update_scratch',
  'update_session_status',
  'update_system_proxy_settings',
  'update_system_rendering_settings',
  'update_tag',
  'update_task',
  'update_version_control_settings',
  'update_workspace',
  'upload_image',
  'upload_image_for_task',
  'upload_image_for_workspace',
  'weixin_check_qrcode',
  'weixin_get_qrcode',
  'workflow_accept_candidate',
  'workflow_cancel',
  'workflow_complete_step',
  'workflow_debug',
  'workflow_decide',
  'workflow_events',
  'workflow_fork',
  'workflow_list',
  'workflow_pause',
  'workflow_pause_step',
  'workflow_publish',
  'workflow_resume',
  'workflow_resume_run',
  'workflow_show',
  'workflow_source_read',
  'workflow_source_write',
  'workflow_start',
  'workflow_step_input',
  'workflow_steps',
  'workflow_validate',
  'workflow_version',
  'workflow_versions',
  'write_pasted_image_asset',
  'write_terminal',
  'write_workspace_conflict_resolution',
] as const;

export const DESKTOP_SHELL_COMMANDS = [
  'open_in_editor',
  'open_project_in_editor',
  'show_desktop_toast',
  'start_web_server',
  'stop_web_server',
  'host_client_connect',
  'host_client_disconnect',
  'host_client_call',
  'remote_desktop_connect',
  'remote_desktop_disconnect',
  'remote_desktop_call',
  'remote_desktop_capabilities',
  'remote_desktop_listen',
  'remote_desktop_subscribe',
  'remote_desktop_cancel_subscription',
  'create_ssh_tunnel',
  'close_ssh_tunnel',
  'backup_create',
  'backup_restore',
  'open_devtools',
  'plugin_dev_connection',
  'activate_desktop_toast',
  'set_app_icon',
  'update_tray_badge',
  'host_client_delete',
  'revoke_host_device',
  'fixture_delegate',
  'fixture_reset',
  'backup_cancel',
  'backup_inspect',
  'backup_restore_stage',
  'browser_apply_intent',
  'browser_close_tab',
  'browser_create_tab',
  'browser_get_tab',
  'cancel_create_host_tunnel',
  'check_existing_host_tunnel',
  'confirm_create_host_tunnel',
  'control_tauri_inspector',
  'create_host_device_pairing',
  'desktop_toast_window_ready',
  'exit_app',
  'generate_web_service_token',
  'get_host_tunnel',
  'get_tauri_inspector_status',
  'get_web_server_status',
  'get_web_service_config',
  'health_check',
  'host_client_discover',
  'host_client_status',
  'install_tauri_inspector',
  'is_main_window_focused',
  'list_host_devices',
  'open_external_terminal',
  'open_repo_in_editor',
  'open_settings_window',
  'open_workspace_in_editor',
  'probe_web_service_port',
  'remove_saved_host_tunnel',
  'reveal_in_file_manager',
  'select_saved_host_tunnel',
  'set_host_tunnel_enabled',
  'start_create_host_tunnel',
  'take_tauri_inspector_capture',
  'update_web_service_config',
  'plugin_control_import_cli',
] as const;

export const HOST_CAPABILITY_SCOPES = [
  'application.call',
  'artifact.preview',
  'artifact.read',
  'automation.read',
  'automation.write',
  'conversation.attach',
  'conversation.cancel',
  'conversation.permission',
  'conversation.question',
  'conversation.read',
  'conversation.steer',
  'conversation.write',
  'delegation.cancel',
  'delegation.read',
  'plugin.read',
  'plugin.surface',
  'plugin.write',
  'workflow.approve',
  'workflow.read',
  'workflow.run',
  'workflow.write',
] as const;

export const HOST_COMMAND_DESCRIPTORS = [
  { name: 'abort_conflicts_workspace', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'add_project_repository', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'add_repo_remote', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_auth_mode', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_auth_mode_set', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_cancel_prompt', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_capability_catalog', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_capability_catalog_fresh', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_connect', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_connection_snapshot', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_delete_remote_session', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_discard_prepared_session', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_disconnect', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_import_local_history', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_import_local_history_batch', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_import_remote_session', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_list_live_terminals', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_list_local_history', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_list_remote_sessions', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_list_session_commands', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_load_session', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_local_history_import_snapshot', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_account_flow', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_actions', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_apply_update', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_bar', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_cancel_operation', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_check_update', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_clear_diagnostics', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_config_file_write', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_config_read', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_config_write', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_detail', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_diagnostics', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_discovery_progress', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_environment', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_environment_diagnostics', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_environment_write', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_install_version', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_mark_diagnostics_read', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_preflight', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_refresh', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_remove', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_reorder', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_repair', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_rollback', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_run_action', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_set_enabled', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_management_uninstall', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_model_provider_bind', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_model_provider_catalog', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_model_provider_delete', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_model_provider_import', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_model_provider_import_preview', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_model_provider_probe', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_model_provider_save', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_model_providers', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_new_session', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_plan_usage', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_prepare_session', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_refresh_capability_catalog', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_registry_add_and_install', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_registry_refresh', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_registry_view', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_reset_to_checkpoint', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_respond_permission', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_resume_session', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_runtime_snapshot', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_scan_local_history', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_send_prompt', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_session_defaults', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_set_prepared_session_config', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_set_prepared_session_mode', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_set_session_defaults', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_terminal_snapshot', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_user_definition_add_and_install', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_user_definition_detail', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'agent_user_definition_update', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'apply_workspace_stash', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'artifact_close_preview', scope: 'artifact.preview', kind: 'domain', argShape: 'compat' },
  { name: 'artifact_list', scope: 'artifact.read', kind: 'domain', argShape: 'compat' },
  { name: 'artifact_open_preview', scope: 'artifact.preview', kind: 'domain', argShape: 'compat' },
  { name: 'attach_terminal', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'attach_workspace_pr', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'attention_inbox_list', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'automation_cancel_run', scope: 'automation.write', kind: 'domain', argShape: 'compat' },
  { name: 'automation_create', scope: 'automation.write', kind: 'domain', argShape: 'compat' },
  { name: 'automation_create_workflow', scope: 'automation.write', kind: 'domain', argShape: 'compat' },
  { name: 'automation_delete', scope: 'automation.write', kind: 'domain', argShape: 'compat' },
  { name: 'automation_engine_status', scope: 'automation.read', kind: 'domain', argShape: 'compat' },
  { name: 'automation_export_spec', scope: 'automation.read', kind: 'domain', argShape: 'compat' },
  { name: 'automation_import_spec', scope: 'automation.write', kind: 'domain', argShape: 'compat' },
  { name: 'automation_list', scope: 'automation.read', kind: 'domain', argShape: 'compat' },
  { name: 'automation_mark_seen', scope: 'automation.write', kind: 'domain', argShape: 'compat' },
  { name: 'automation_preview_next_runs', scope: 'automation.read', kind: 'domain', argShape: 'compat' },
  { name: 'automation_run_now', scope: 'automation.write', kind: 'domain', argShape: 'compat' },
  { name: 'automation_runs', scope: 'automation.read', kind: 'domain', argShape: 'compat' },
  { name: 'automation_set_enabled', scope: 'automation.write', kind: 'domain', argShape: 'compat' },
  { name: 'automation_templates', scope: 'automation.read', kind: 'domain', argShape: 'compat' },
  { name: 'automation_unseen_failures', scope: 'automation.read', kind: 'domain', argShape: 'compat' },
  { name: 'automation_update', scope: 'automation.write', kind: 'domain', argShape: 'compat' },
  { name: 'automation_update_workflow', scope: 'automation.write', kind: 'domain', argShape: 'compat' },
  { name: 'change_workspace_target_branch', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'check_app_release', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'check_editor_availability', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'check_git_repo_path', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'checkout_repo_branch', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'checkout_workspace_branch', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'clear_local_app_data', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'clone_repo', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'close_terminal', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'codex_model_catalog', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'codex_model_catalog_apply', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'codex_model_catalog_config', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'codex_poll_device_code', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'codex_request_device_code', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'commit_repo_changes', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'commit_workspace_changes', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'connect_chat_channel', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'continue_conflicts_workspace', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'continue_rebase_workspace', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'conversation_archive', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_attach', scope: 'conversation.attach', kind: 'core', argShape: 'request' },
  { name: 'conversation_cancel_turn', scope: 'conversation.cancel', kind: 'core', argShape: 'compat' },
  { name: 'conversation_catalog', scope: 'conversation.read', kind: 'core', argShape: 'compat' },
  { name: 'conversation_checkpoint_file_changes_preview', scope: 'conversation.read', kind: 'domain', argShape: 'compat' },
  { name: 'conversation_child_create', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_close', scope: 'conversation.write', kind: 'domain', argShape: 'compat' },
  { name: 'conversation_create', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_delete', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_detail', scope: 'conversation.read', kind: 'domain', argShape: 'compat' },
  { name: 'conversation_ensure_session_controls', scope: 'conversation.write', kind: 'domain', argShape: 'compat' },
  { name: 'conversation_events_since', scope: 'conversation.read', kind: 'domain', argShape: 'compat' },
  { name: 'conversation_export', scope: 'conversation.read', kind: 'domain', argShape: 'compat' },
  { name: 'conversation_export_html', scope: 'conversation.read', kind: 'domain', argShape: 'compat' },
  { name: 'conversation_export_markdown', scope: 'conversation.read', kind: 'domain', argShape: 'compat' },
  { name: 'conversation_fork', scope: 'conversation.write', kind: 'domain', argShape: 'compat' },
  { name: 'conversation_import', scope: 'conversation.write', kind: 'domain', argShape: 'compat' },
  { name: 'conversation_input_cancel', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_input_list', scope: 'conversation.read', kind: 'core', argShape: 'compat' },
  { name: 'conversation_input_reorder', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_input_submit', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_input_update', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_list', scope: 'conversation.read', kind: 'core', argShape: 'compat' },
  { name: 'conversation_list_feedback', scope: 'conversation.read', kind: 'core', argShape: 'compat' },
  { name: 'conversation_list_recent', scope: 'conversation.read', kind: 'core', argShape: 'compat' },
  { name: 'conversation_output', scope: 'conversation.read', kind: 'core', argShape: 'compat' },
  { name: 'conversation_rebind_session', scope: 'conversation.write', kind: 'domain', argShape: 'compat' },
  { name: 'conversation_relation_list', scope: 'conversation.read', kind: 'core', argShape: 'compat' },
  { name: 'conversation_rename', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_respond_permission', scope: 'conversation.permission', kind: 'core', argShape: 'compat' },
  { name: 'conversation_respond_question', scope: 'conversation.question', kind: 'core', argShape: 'compat' },
  { name: 'conversation_search', scope: 'conversation.read', kind: 'domain', argShape: 'compat' },
  { name: 'conversation_set_pinned', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_set_session_config_option', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_set_session_mode', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_set_status', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_slash_commands', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_start_turn', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_steer', scope: 'conversation.steer', kind: 'core', argShape: 'compat' },
  { name: 'conversation_submit_feedback', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_timeline_page', scope: 'conversation.read', kind: 'domain', argShape: 'compat' },
  { name: 'conversation_truncate_to_turn', scope: 'conversation.write', kind: 'domain', argShape: 'compat' },
  { name: 'conversation_workspace_create', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'conversation_workspace_entries', scope: 'conversation.write', kind: 'core', argShape: 'compat' },
  { name: 'copy_item', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'crash_report_delete', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'crash_report_read', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'crash_reports_list', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_chat_channel', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_directory', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_instruction', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_project', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_project_root_session', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_project_session', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_repo_branch', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_scratch', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_session', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_tag', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_task', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_task_and_start', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_terminal', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_workflow_debug_workspace', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_workspace', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_workspace_branch', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_workspace_from_pr', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'create_workspace_pr', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'cursor_model_catalog', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'delegation_cancel', scope: 'delegation.cancel', kind: 'domain', argShape: 'compat' },
  { name: 'delete_agent_skill', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'delete_chat_channel', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'delete_chat_channel_token', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'delete_file', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'delete_image', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'delete_instruction', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'delete_project', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'delete_project_repository', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'delete_repo_branch', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'delete_scratch', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'delete_session', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'delete_tag', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'delete_task', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'delete_workspace', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'delete_workspace_branch', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'detect_git_version', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'disconnect_chat_channel', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'drop_workspace_stash', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'dsh_plugin_add', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'dsh_plugin_remove', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'dsh_plugins', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'dsh_provider_delete', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'dsh_provider_discover_models', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'dsh_provider_save', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'dsh_providers', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'enhance_prompt', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'ensure_project_workspace', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'fetch_repo', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'fetch_workspace', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_chat_channel_has_token', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_chat_command_prefix', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_chat_event_filter', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_chat_event_webhooks', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_chat_include_prompt_text', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_chat_message_language', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_claude_settings', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_claude_settings_path', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_execution_process', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_execution_process_repo_states', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_file_at_head', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_file_tree', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_first_user_message', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_frontend_preferences', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_github_cli_status', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_log_settings', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_logs_dir', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_market_skill_detail', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_profiles', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_project', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_project_repositories', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_project_usage_statistics', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_project_workspaces', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_project_worktree_settings', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_projects', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_recent_logs', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_recent_repos', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_repo', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_repo_branches', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_repo_commit_detail', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_repo_commit_diffs', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_repo_file_diffs', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_repo_git_log', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_repo_git_status', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_repo_remotes', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_repos', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_repos_batch', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_scratch', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_session', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_session_summaries', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_sessions', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_settings_file_path', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_system_proxy_settings', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_system_rendering_settings', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_tags', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_task', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_task_image_metadata', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_task_images', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_user_system_info', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_version_control_settings', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_workspace', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_workspace_branch_status', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_workspace_children', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_workspace_commit_detail', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_workspace_commit_diffs', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_workspace_commit_graph', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_workspace_commit_history', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_workspace_conflict_file', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_workspace_count', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_workspace_file_diffs', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_workspace_git_log', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_workspace_git_status', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_workspace_image_metadata', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_workspace_pr_comments', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_workspace_repos', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_workspaces', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'get_worktree_cleanup_status', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'gh_cli_setup', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'git_cherry_pick', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'git_create_branch_at_commit', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'git_reset_to_commit', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'git_revert_commit', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'grok_plugin_add', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'grok_plugin_remove', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'grok_plugins', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'init_repo', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'init_repo_at_path', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'install_github_cli', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'install_market_skill', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'install_official_instruction', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'install_version_control_tools', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'kimi_model_catalog', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'list_agent_skills', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'list_chat_channel_message_logs', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'list_chat_channel_statuses', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'list_chat_channels', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'list_directory', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'list_directory_children', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'list_git_repos', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'list_instructions', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'list_official_instructions', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'list_open_prs', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'list_prompt_enhancement_models', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'list_repo_issues', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'list_workspace_stashes', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'logout_github_cli', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'mark_session_viewed', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'mark_workspace_seen', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'mcp_get_marketplace_server_detail', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'mcp_install_marketplace_server', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'mcp_list_marketplaces', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'mcp_scan_local', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'mcp_search_marketplace', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'mcp_uninstall_server', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'mcp_upsert_local_server', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'merge_workspace', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'move_item', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'open_github_cli_login', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'opencode_plugin_add', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'opencode_plugin_install', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'opencode_plugin_list', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'opencode_plugin_uninstall', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'opencode_provider_catalog', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'opencode_provider_connect', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'opencode_provider_connections', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'opencode_provider_disconnect', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'opencode_provider_import', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'opencode_provider_set_enabled', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'pi_command_validate', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'pi_configuration', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'pi_credentials_save', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'pi_plugin_add', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'pi_plugin_remove', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'pi_plugins', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'pi_runtime_save', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'play_notification_sound', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_action_catalog', scope: 'plugin.read', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_check_updates', scope: 'plugin.read', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_close_file_preview', scope: 'artifact.preview', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_contribution_catalog', scope: 'plugin.read', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_control_catalog', scope: 'plugin.read', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_control_configure_agents', scope: 'plugin.write', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_control_configure_mcp', scope: 'plugin.write', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_control_contributions', scope: 'plugin.read', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_control_gc_runtimes', scope: 'plugin.write', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_control_grant_permissions', scope: 'plugin.write', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_control_import', scope: 'plugin.write', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_control_install_runtime', scope: 'plugin.write', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_control_logs', scope: 'plugin.read', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_control_preview_import', scope: 'plugin.write', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_control_rollback', scope: 'plugin.write', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_control_set_enabled', scope: 'plugin.write', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_control_uninstall', scope: 'plugin.write', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_control_update', scope: 'plugin.write', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_install', scope: 'plugin.write', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_invoke_contribution', scope: 'plugin.surface', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_marketplace_catalog', scope: 'plugin.read', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_marketplace_index', scope: 'plugin.read', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_marketplace_install', scope: 'plugin.write', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_marketplace_listing', scope: 'plugin.read', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_open_file_preview', scope: 'artifact.preview', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_product_detail', scope: 'plugin.read', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_renew_file_preview', scope: 'artifact.preview', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_resolve_file_opener', scope: 'plugin.read', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_save_config', scope: 'plugin.write', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_surface_invoke', scope: 'plugin.surface', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_surface_open', scope: 'plugin.surface', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_surface_revoke', scope: 'plugin.surface', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_uninstall', scope: 'plugin.write', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_update', scope: 'plugin.write', kind: 'domain', argShape: 'compat' },
  { name: 'plugin_workflow_catalog', scope: 'plugin.read', kind: 'domain', argShape: 'compat' },
  { name: 'pop_workspace_stash', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'pull_repo', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'pull_workspace_branch', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'push_repo', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'push_workspace_branch', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'read_agent_skill', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'read_binary_asset', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'read_file_content', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'read_file_with_truncation', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'read_local_skill', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'rebase_back_workspace', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'rebase_workspace', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'refresh_prompt_enhancement_catalogs', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'register_repo', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'remove_repo_remote', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'rename_session', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'rename_workspace_branch', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'reset_session_process', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'resize_terminal', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'respond_to_approval', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'revert_repo_all', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'revert_repo_file', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'revert_workspace_all', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'revert_workspace_file', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'run_archive_script', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'run_cleanup_script', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'run_setup_script', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'save_agent_skill', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'save_chat_channel_token', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'save_file_content', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'scan_local_skills', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'search_project_files', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'search_repo', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'search_skill_market', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'search_workspace_text', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'set_chat_command_prefix', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'set_chat_event_filter', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'set_chat_event_webhooks', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'set_chat_include_prompt_text', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'set_chat_message_language', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'set_log_settings', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'set_repo_remote_url', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'set_session_pinned', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'set_skill_hosting', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'show_workspace_stash', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'stage_repo_all', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'stage_repo_file', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'stage_workspace_all', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'stage_workspace_file', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'start_workspace_dev_server', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'stash_workspace', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'stop_execution_process', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'stop_workspace_execution', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'subscribe_conversation_stream', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'subscribe_diff_stream', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'subscribe_execution_processes_stream', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'subscribe_file_tree_stream', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'subscribe_log_stream', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'subscribe_project_workspaces_stream', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'subscribe_projects_stream', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'subscribe_scratch_stream', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'subscribe_slash_commands_stream', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'test_chat_channel', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'test_git_path', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'trash_item', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'uninstall_skill', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'unstage_repo_file', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'unstage_workspace_file', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_chat_channel', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_claude_settings', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_config', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_frontend_preferences', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_instruction', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_profiles', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_project', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_project_worktree_settings', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_repo', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_scratch', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_session_status', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_system_proxy_settings', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_system_rendering_settings', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_tag', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_task', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_version_control_settings', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'update_workspace', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'upload_image', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'upload_image_for_task', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'upload_image_for_workspace', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'weixin_check_qrcode', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'weixin_get_qrcode', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'workflow_accept_candidate', scope: 'workflow.approve', kind: 'core', argShape: 'compat' },
  { name: 'workflow_cancel', scope: 'workflow.run', kind: 'core', argShape: 'compat' },
  { name: 'workflow_complete_step', scope: 'workflow.run', kind: 'core', argShape: 'compat' },
  { name: 'workflow_debug', scope: 'workflow.run', kind: 'core', argShape: 'compat' },
  { name: 'workflow_decide', scope: 'workflow.approve', kind: 'core', argShape: 'compat' },
  { name: 'workflow_events', scope: 'workflow.read', kind: 'core', argShape: 'compat' },
  { name: 'workflow_fork', scope: 'workflow.run', kind: 'core', argShape: 'compat' },
  { name: 'workflow_list', scope: 'workflow.read', kind: 'core', argShape: 'compat' },
  { name: 'workflow_pause', scope: 'workflow.run', kind: 'core', argShape: 'compat' },
  { name: 'workflow_pause_step', scope: 'workflow.run', kind: 'core', argShape: 'compat' },
  { name: 'workflow_publish', scope: 'workflow.write', kind: 'core', argShape: 'compat' },
  { name: 'workflow_resume', scope: 'workflow.run', kind: 'core', argShape: 'compat' },
  { name: 'workflow_resume_run', scope: 'workflow.run', kind: 'core', argShape: 'compat' },
  { name: 'workflow_show', scope: 'workflow.read', kind: 'core', argShape: 'compat' },
  { name: 'workflow_source_read', scope: 'workflow.read', kind: 'domain', argShape: 'compat' },
  { name: 'workflow_source_write', scope: 'workflow.write', kind: 'domain', argShape: 'compat' },
  { name: 'workflow_start', scope: 'workflow.run', kind: 'core', argShape: 'compat' },
  { name: 'workflow_step_input', scope: 'workflow.run', kind: 'core', argShape: 'compat' },
  { name: 'workflow_steps', scope: 'workflow.read', kind: 'core', argShape: 'compat' },
  { name: 'workflow_validate', scope: 'workflow.write', kind: 'core', argShape: 'compat' },
  { name: 'workflow_version', scope: 'workflow.read', kind: 'core', argShape: 'compat' },
  { name: 'workflow_versions', scope: 'workflow.read', kind: 'core', argShape: 'compat' },
  { name: 'write_pasted_image_asset', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'write_terminal', scope: 'application.call', kind: 'domain', argShape: 'compat' },
  { name: 'write_workspace_conflict_resolution', scope: 'application.call', kind: 'domain', argShape: 'compat' },
] as const;

export const HOST_EVENT_CHANNELS = [
  { prefix: 'conversation-events', durability: 'invalidation', scope: 'conversation.read' },
  { prefix: 'workspace-sessions-changed', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'agent-management-event', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'agent-management-snapshot-invalidated', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'agent-management-discovery-progress', durability: 'best_effort', scope: 'application.call' },
  { prefix: 'agent-terminal-events', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'desktop-session-attention', durability: 'best_effort', scope: 'application.call' },
  { prefix: 'file-tree-stream', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'projects-stream', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'project-workspaces-stream', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'execution-processes-stream', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'diff-stream', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'conversation-stream', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'scratch-stream', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'slash-commands-stream', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'log-stream', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'vibex://settings-file-changed', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'theme-changed', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'log-settings://changed', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'logs://appended', durability: 'best_effort', scope: 'application.call' },
  { prefix: 'local-history-import-progress', durability: 'best_effort', scope: 'application.call' },
  { prefix: 'local-history-scan-progress', durability: 'best_effort', scope: 'application.call' },
  { prefix: 'agent-events', durability: 'invalidation', scope: 'application.call' },
  { prefix: 'terminal-output', durability: 'best_effort', scope: 'application.call' },
] as const;

export type HostCommand = (typeof HOST_COMMANDS)[number];
export type DesktopShellCommand = (typeof DESKTOP_SHELL_COMMANDS)[number];
