use std::{str::FromStr, sync::Arc};

use async_trait::async_trait;

use crate::{ApplicationError, Principal};

macro_rules! domain_commands {
    ($($variant:ident => $name:literal / $scope:literal),+ $(,)?) => {
        /// Closed set of non-Conversation product commands supported by remote hosts.
        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum DomainCommand {
            $($variant,)+
        }

        impl DomainCommand {
            pub const ALL: &'static [Self] = &[$(Self::$variant,)+];

            pub fn capability_scopes() -> Vec<&'static str> {
                let mut scopes = std::collections::BTreeSet::new();
                for command in Self::ALL {
                    scopes.insert(command.required_scope());
                }
                for scope in [
                    "conversation.read",
                    "conversation.write",
                    "conversation.attach",
                    "conversation.permission",
                    "conversation.question",
                    "conversation.cancel",
                    "conversation.steer",
                    "workflow.read",
                    "workflow.write",
                    "workflow.run",
                    "workflow.approve",
                    "device.pair",
                    "device.revoke",
                    "notification.summary",
                    "offline.read",
                    "preview.proxy",
                    "delegation.read",
                ] {
                    scopes.insert(scope);
                }
                scopes.into_iter().collect()
            }

            pub const fn as_str(self) -> &'static str {
                match self {
                    $(Self::$variant => $name,)+
                }
            }

            pub const fn required_scope(self) -> &'static str {
                match self {
                    $(Self::$variant => $scope,)+
                }
            }
        }

        impl FromStr for DomainCommand {
            type Err = ();

            fn from_str(value: &str) -> Result<Self, Self::Err> {
                Self::ALL
                    .iter()
                    .copied()
                    .find(|command| command.as_str() == value)
                    .ok_or(())
            }
        }
    };
}

domain_commands! {
    PluginActionCatalog => "plugin_action_catalog" / "plugin.read",
    PluginControlCatalog => "plugin_control_catalog" / "plugin.read",
    PluginProductDetail => "plugin_product_detail" / "plugin.read",
    PluginSaveConfig => "plugin_save_config" / "plugin.write",
    PluginContributionCatalog => "plugin_contribution_catalog" / "plugin.read",
    PluginResolveFileOpener => "plugin_resolve_file_opener" / "plugin.read",
    PluginOpenFilePreview => "plugin_open_file_preview" / "artifact.preview",
    PluginCloseFilePreview => "plugin_close_file_preview" / "artifact.preview",
    PluginRenewFilePreview => "plugin_renew_file_preview" / "artifact.preview",
    PluginControlSetEnabled => "plugin_control_set_enabled" / "plugin.write",
    PluginControlGrantPermissions => "plugin_control_grant_permissions" / "plugin.write",
    PluginControlInstallRuntime => "plugin_control_install_runtime" / "plugin.write",
    PluginControlImport => "plugin_control_import" / "plugin.write",
    PluginMarketplaceCatalog => "plugin_marketplace_catalog" / "plugin.read",
    PluginMarketplaceListing => "plugin_marketplace_listing" / "plugin.read",
    PluginMarketplaceInstall => "plugin_marketplace_install" / "plugin.write",
    PluginCheckUpdates => "plugin_check_updates" / "plugin.read",
    PluginControlLogs => "plugin_control_logs" / "plugin.read",
    PluginControlUninstall => "plugin_control_uninstall" / "plugin.write",
    PluginControlGcRuntimes => "plugin_control_gc_runtimes" / "plugin.write",
    PluginSurfaceOpen => "plugin_surface_open" / "plugin.surface",
    PluginSurfaceInvoke => "plugin_surface_invoke" / "plugin.surface",
    PluginSurfaceRevoke => "plugin_surface_revoke" / "plugin.surface",
    ProjectList => "get_projects" / "application.call",
    ProjectGet => "get_project" / "application.call",
    ProjectCreate => "create_project" / "application.call",
    ProjectUpdate => "update_project" / "application.call",
    ProjectDelete => "delete_project" / "application.call",
    ProjectSearchFiles => "search_project_files" / "application.call",
    ProjectRepositories => "get_project_repositories" / "application.call",
    ProjectAddRepository => "add_project_repository" / "application.call",
    ProjectDeleteRepository => "delete_project_repository" / "application.call",
    RepoList => "get_repos" / "application.call",
    RepoGet => "get_repo" / "application.call",
    RepoRegister => "register_repo" / "application.call",
    RepoRecent => "get_recent_repos" / "application.call",
    RepoInit => "init_repo" / "application.call",
    RepoCheckPath => "check_git_repo_path" / "application.call",
    RepoClone => "clone_repo" / "application.call",
    RepoBranches => "get_repo_branches" / "application.call",
    RepoGitStatus => "get_repo_git_status" / "application.call",
    RepoFileDiffs => "get_repo_file_diffs" / "application.call",
    RepoStageFile => "stage_repo_file" / "application.call",
    RepoUnstageFile => "unstage_repo_file" / "application.call",
    RepoRevertFile => "revert_repo_file" / "application.call",
    RepoStageAll => "stage_repo_all" / "application.call",
    RepoRevertAll => "revert_repo_all" / "application.call",
    RepoCommit => "commit_repo_changes" / "application.call",
    RepoGitLog => "get_repo_git_log" / "application.call",
    RepoCheckoutBranch => "checkout_repo_branch" / "application.call",
    RepoCreateBranch => "create_repo_branch" / "application.call",
    RepoDeleteBranch => "delete_repo_branch" / "application.call",
    WorkspaceList => "get_workspaces" / "application.call",
    WorkspaceListByProject => "get_project_workspaces" / "application.call",
    WorkspaceGet => "get_workspace" / "application.call",
    WorkspaceCount => "get_workspace_count" / "application.call",
    WorkspaceRepos => "get_workspace_repos" / "application.call",
    WorkspaceGitStatus => "get_workspace_git_status" / "application.call",
    WorkspaceStageFile => "stage_workspace_file" / "application.call",
    WorkspaceStageAll => "stage_workspace_all" / "application.call",
    WorkspaceUnstageFile => "unstage_workspace_file" / "application.call",
    WorkspaceRevertFile => "revert_workspace_file" / "application.call",
    WorkspaceRevertAll => "revert_workspace_all" / "application.call",
    WorkspaceFileDiffs => "get_workspace_file_diffs" / "application.call",
    WorkspaceCommit => "commit_workspace_changes" / "application.call",
    WorkspaceGitLog => "get_workspace_git_log" / "application.call",
    WorkspaceCommitDetail => "get_workspace_commit_detail" / "application.call",
    WorkspaceCheckoutBranch => "checkout_workspace_branch" / "application.call",
    WorkspaceCreateBranch => "create_workspace_branch" / "application.call",
    WorkspaceDeleteBranch => "delete_workspace_branch" / "application.call",
    WorkspaceCreate => "create_workspace" / "application.call",
    WorkspaceUpdate => "update_workspace" / "application.call",
    WorkspaceDelete => "delete_workspace" / "application.call",
    WorkspaceMarkSeen => "mark_workspace_seen" / "application.call",
    WorkspaceChildren => "get_workspace_children" / "application.call",
    WorkspaceBranchStatus => "get_workspace_branch_status" / "application.call",
    WorkspaceCommitHistory => "get_workspace_commit_history" / "application.call",
    WorkspaceCommitGraph => "get_workspace_commit_graph" / "application.call",
    WorkspaceCommitDiffs => "get_workspace_commit_diffs" / "application.call",
    WorkspacePush => "push_workspace_branch" / "application.call",
    WorkspacePull => "pull_workspace_branch" / "application.call",
    WorkspaceFetch => "fetch_workspace" / "application.call",
    WorkspaceMerge => "merge_workspace" / "application.call",
    WorkspaceRebase => "rebase_workspace" / "application.call",
    WorkspaceRebaseBack => "rebase_back_workspace" / "application.call",
    WorkspaceContinueRebase => "continue_rebase_workspace" / "application.call",
    WorkspaceAbortConflicts => "abort_conflicts_workspace" / "application.call",
    WorkspaceStash => "stash_workspace" / "application.call",
    WorkspaceStashList => "list_workspace_stashes" / "application.call",
    WorkspaceStashApply => "apply_workspace_stash" / "application.call",
    WorkspaceStashPop => "pop_workspace_stash" / "application.call",
    WorkspaceStashDrop => "drop_workspace_stash" / "application.call",
    WorkspaceRenameBranch => "rename_workspace_branch" / "application.call",
    WorkspaceChangeTargetBranch => "change_workspace_target_branch" / "application.call",
    ConversationDetail => "conversation_detail" / "conversation.read",
    ConversationEventsSince => "conversation_events_since" / "conversation.read",
    ConversationEnsureSessionControls => "conversation_ensure_session_controls" / "conversation.write",
    SessionList => "get_sessions" / "application.call",
    SessionSummaries => "get_session_summaries" / "application.call",
    SessionGet => "get_session" / "application.call",
    SessionCreate => "create_session" / "application.call",
    SessionCreateProjectRoot => "create_project_root_session" / "application.call",
    SessionCreateProject => "create_project_session" / "application.call",
    SessionEnsureWorkspace => "ensure_project_workspace" / "application.call",
    SessionRename => "rename_session" / "application.call",
    SessionUpdateStatus => "update_session_status" / "application.call",
    SessionMarkViewed => "mark_session_viewed" / "application.call",
    SessionSetPinned => "set_session_pinned" / "application.call",
    SessionDelete => "delete_session" / "application.call",
    FileTree => "get_file_tree" / "application.call",
    FileRead => "read_file_content" / "application.call",
    FileSave => "save_file_content" / "application.call",
    FileDelete => "delete_file" / "application.call",
    FileListChildren => "list_directory_children" / "application.call",
    FileReadTruncated => "read_file_with_truncation" / "application.call",
    FileCopy => "copy_item" / "application.call",
    FileMove => "move_item" / "application.call",
    FileCreateDirectory => "create_directory" / "application.call",
    FileSearchText => "search_workspace_text" / "application.call",
    FileListDirectory => "list_directory" / "application.call",
    FileListGitRepos => "list_git_repos" / "application.call",
    FileAtHead => "get_file_at_head" / "application.call",
    TerminalCreate => "create_terminal" / "application.call",
    TerminalWrite => "write_terminal" / "application.call",
    TerminalResize => "resize_terminal" / "application.call",
    TerminalClose => "close_terminal" / "application.call",
    TerminalAttach => "attach_terminal" / "application.call",
    AgentManagementBar => "agent_management_bar" / "application.call",
    AgentManagementDetail => "agent_management_detail" / "application.call",
    AgentManagementSetEnabled => "agent_management_set_enabled" / "application.call",
    AgentManagementRefresh => "agent_management_refresh" / "application.call",
    AgentCapabilityCatalog => "agent_capability_catalog" / "application.call",
    AgentSkillsList => "list_agent_skills" / "application.call",
    UserSystemInfo => "get_user_system_info" / "application.call",
    ArtifactList => "artifact_list" / "artifact.read",
    ArtifactOpenPreview => "artifact_open_preview" / "artifact.preview",
    ArtifactClosePreview => "artifact_close_preview" / "artifact.preview",
    AutomationList => "automation_list" / "automation.read",
    AutomationEngineStatus => "automation_engine_status" / "automation.read",
    AutomationCreate => "automation_create" / "automation.write",
    AutomationCreateWorkflow => "automation_create_workflow" / "automation.write",
    AutomationUpdate => "automation_update" / "automation.write",
    AutomationSetEnabled => "automation_set_enabled" / "automation.write",
    AutomationDelete => "automation_delete" / "automation.write",
    AutomationRunNow => "automation_run_now" / "automation.write",
    AutomationCancelRun => "automation_cancel_run" / "automation.write",
    AutomationRuns => "automation_runs" / "automation.read",
    AutomationPreviewNextRuns => "automation_preview_next_runs" / "automation.read",
    AutomationTemplates => "automation_templates" / "automation.read",
    AutomationUnseenFailures => "automation_unseen_failures" / "automation.read",
    AutomationMarkSeen => "automation_mark_seen" / "automation.write",
    AutomationExportSpec => "automation_export_spec" / "automation.read",
    AutomationImportSpec => "automation_import_spec" / "automation.write",
    AutomationUpdateWorkflow => "automation_update_workflow" / "automation.write",
    DelegationCancel => "delegation_cancel" / "delegation.cancel",
    AttentionInboxList => "attention_inbox_list" / "application.call",
    ScratchGet => "get_scratch" / "application.call",
    ScratchCreate => "create_scratch" / "application.call",
    ScratchUpdate => "update_scratch" / "application.call",
    ScratchDelete => "delete_scratch" / "application.call",
    TagList => "get_tags" / "application.call",
    TagCreate => "create_tag" / "application.call",
    TagUpdate => "update_tag" / "application.call",
    TagDelete => "delete_tag" / "application.call",
    TaskGet => "get_task" / "application.call",
    TaskCreate => "create_task" / "application.call",
    TaskCreateAndStart => "create_task_and_start" / "application.call",
    TaskUpdate => "update_task" / "application.call",
    TaskDelete => "delete_task" / "application.call",
    RepoUpdate => "update_repo" / "application.call",
    RepoPush => "push_repo" / "application.call",
    RepoPull => "pull_repo" / "application.call",
    RepoFetch => "fetch_repo" / "application.call",
    RepoRemotes => "get_repo_remotes" / "application.call",
    RepoAddRemote => "add_repo_remote" / "application.call",
    RepoRemoveRemote => "remove_repo_remote" / "application.call",
    RepoSetRemoteUrl => "set_repo_remote_url" / "application.call",
    RepoCommitDetail => "get_repo_commit_detail" / "application.call",
    RepoCommitDiffs => "get_repo_commit_diffs" / "application.call",
    RepoSearch => "search_repo" / "application.call",
    RepoIssues => "list_repo_issues" / "application.call",
    RepoOpenPrs => "list_open_prs" / "application.call",
    WorkflowSourceRead => "workflow_source_read" / "workflow.read",
    WorkflowSourceWrite => "workflow_source_write" / "workflow.write",
    AgentRefreshCapabilityCatalog => "agent_refresh_capability_catalog" / "application.call",
    AgentCapabilityCatalogFresh => "agent_capability_catalog_fresh" / "application.call",
    AgentListLiveTerminals => "agent_list_live_terminals" / "application.call",
    AgentPlanUsage => "agent_plan_usage" / "application.call",
    FrontendPreferencesGet => "get_frontend_preferences" / "application.call",
    FrontendPreferencesUpdate => "update_frontend_preferences" / "application.call",
    ProjectWorktreeSettingsGet => "get_project_worktree_settings" / "application.call",
    ProjectWorktreeSettingsUpdate => "update_project_worktree_settings" / "application.call",
    ReadBinaryAsset => "read_binary_asset" / "application.call",
    SubscribeDiffStream => "subscribe_diff_stream" / "application.call",
    SubscribeConversationStream => "subscribe_conversation_stream" / "application.call",
    SubscribeExecutionProcessesStream => "subscribe_execution_processes_stream" / "application.call",
    SubscribeProjectWorkspacesStream => "subscribe_project_workspaces_stream" / "application.call",
    SubscribeProjectsStream => "subscribe_projects_stream" / "application.call",
    SubscribeFileTreeStream => "subscribe_file_tree_stream" / "application.call",
    SubscribeScratchStream => "subscribe_scratch_stream" / "application.call",
    SubscribeLogStream => "subscribe_log_stream" / "application.call",
    SubscribeSlashCommandsStream => "subscribe_slash_commands_stream" / "application.call",
    AgentAuthMode => "agent_auth_mode" / "application.call",
    AgentAuthModeSet => "agent_auth_mode_set" / "application.call",
    AgentCancelPrompt => "agent_cancel_prompt" / "application.call",
    AgentConnect => "agent_connect" / "application.call",
    AgentConnectionSnapshot => "agent_connection_snapshot" / "application.call",
    AgentDeleteRemoteSession => "agent_delete_remote_session" / "application.call",
    AgentDiscardPreparedSession => "agent_discard_prepared_session" / "application.call",
    AgentDisconnect => "agent_disconnect" / "application.call",
    AgentImportLocalHistory => "agent_import_local_history" / "application.call",
    AgentImportLocalHistoryBatch => "agent_import_local_history_batch" / "application.call",
    AgentImportRemoteSession => "agent_import_remote_session" / "application.call",
    AgentListLocalHistory => "agent_list_local_history" / "application.call",
    AgentListRemoteSessions => "agent_list_remote_sessions" / "application.call",
    AgentListSessionCommands => "agent_list_session_commands" / "application.call",
    AgentLoadSession => "agent_load_session" / "application.call",
    AgentLocalHistoryImportSnapshot => "agent_local_history_import_snapshot" / "application.call",
    AgentManagementAccountFlow => "agent_management_account_flow" / "application.call",
    AgentManagementActions => "agent_management_actions" / "application.call",
    AgentManagementApplyUpdate => "agent_management_apply_update" / "application.call",
    AgentManagementCancelOperation => "agent_management_cancel_operation" / "application.call",
    AgentManagementCheckUpdate => "agent_management_check_update" / "application.call",
    AgentManagementClearDiagnostics => "agent_management_clear_diagnostics" / "application.call",
    AgentManagementConfigFileWrite => "agent_management_config_file_write" / "application.call",
    AgentManagementConfigRead => "agent_management_config_read" / "application.call",
    AgentManagementConfigWrite => "agent_management_config_write" / "application.call",
    AgentManagementDiagnostics => "agent_management_diagnostics" / "application.call",
    AgentManagementDiscoveryProgress => "agent_management_discovery_progress" / "application.call",
    AgentManagementEnvironment => "agent_management_environment" / "application.call",
    AgentManagementEnvironmentDiagnostics => "agent_management_environment_diagnostics" / "application.call",
    AgentManagementEnvironmentWrite => "agent_management_environment_write" / "application.call",
    AgentManagementInstallVersion => "agent_management_install_version" / "application.call",
    AgentManagementMarkDiagnosticsRead => "agent_management_mark_diagnostics_read" / "application.call",
    AgentManagementPreflight => "agent_management_preflight" / "application.call",
    AgentManagementRemove => "agent_management_remove" / "application.call",
    AgentManagementReorder => "agent_management_reorder" / "application.call",
    AgentManagementRepair => "agent_management_repair" / "application.call",
    AgentManagementRollback => "agent_management_rollback" / "application.call",
    AgentManagementRunAction => "agent_management_run_action" / "application.call",
    AgentManagementUninstall => "agent_management_uninstall" / "application.call",
    AgentModelProviderBind => "agent_model_provider_bind" / "application.call",
    AgentModelProviderCatalog => "agent_model_provider_catalog" / "application.call",
    AgentModelProviderDelete => "agent_model_provider_delete" / "application.call",
    AgentModelProviderImport => "agent_model_provider_import" / "application.call",
    AgentModelProviderImportPreview => "agent_model_provider_import_preview" / "application.call",
    AgentModelProviderProbe => "agent_model_provider_probe" / "application.call",
    AgentModelProviderSave => "agent_model_provider_save" / "application.call",
    AgentModelProviders => "agent_model_providers" / "application.call",
    AgentNewSession => "agent_new_session" / "application.call",
    AgentPrepareSession => "agent_prepare_session" / "application.call",
    AgentRegistryAddAndInstall => "agent_registry_add_and_install" / "application.call",
    AgentRegistryRefresh => "agent_registry_refresh" / "application.call",
    AgentRegistryView => "agent_registry_view" / "application.call",
    AgentResetToCheckpoint => "agent_reset_to_checkpoint" / "application.call",
    AgentRespondPermission => "agent_respond_permission" / "application.call",
    AgentResumeSession => "agent_resume_session" / "application.call",
    AgentRuntimeSnapshot => "agent_runtime_snapshot" / "application.call",
    AgentSendPrompt => "agent_send_prompt" / "application.call",
    AgentSessionDefaults => "agent_session_defaults" / "application.call",
    AgentSetPreparedSessionConfig => "agent_set_prepared_session_config" / "application.call",
    AgentSetPreparedSessionMode => "agent_set_prepared_session_mode" / "application.call",
    AgentSetSessionDefaults => "agent_set_session_defaults" / "application.call",
    AgentTerminalSnapshot => "agent_terminal_snapshot" / "application.call",
    AgentUserDefinitionAddAndInstall => "agent_user_definition_add_and_install" / "application.call",
    AgentUserDefinitionDetail => "agent_user_definition_detail" / "application.call",
    AgentUserDefinitionUpdate => "agent_user_definition_update" / "application.call",
    CodexModelCatalog => "codex_model_catalog" / "application.call",
    CodexModelCatalogApply => "codex_model_catalog_apply" / "application.call",
    CodexModelCatalogConfig => "codex_model_catalog_config" / "application.call",
    CodexPollDeviceCode => "codex_poll_device_code" / "application.call",
    CodexRequestDeviceCode => "codex_request_device_code" / "application.call",
    CreateWorkflowDebugWorkspace => "create_workflow_debug_workspace" / "application.call",
    CursorModelCatalog => "cursor_model_catalog" / "application.call",
    DshPluginAdd => "dsh_plugin_add" / "application.call",
    DshPluginRemove => "dsh_plugin_remove" / "application.call",
    DshPlugins => "dsh_plugins" / "application.call",
    DshProviderDelete => "dsh_provider_delete" / "application.call",
    DshProviderDiscoverModels => "dsh_provider_discover_models" / "application.call",
    DshProviderSave => "dsh_provider_save" / "application.call",
    DshProviders => "dsh_providers" / "application.call",
    GetChatEventWebhooks => "get_chat_event_webhooks" / "application.call",
    GetChatMessageLanguage => "get_chat_message_language" / "application.call",
    GrokPluginAdd => "grok_plugin_add" / "application.call",
    GrokPluginRemove => "grok_plugin_remove" / "application.call",
    GrokPlugins => "grok_plugins" / "application.call",
    KimiModelCatalog => "kimi_model_catalog" / "application.call",
    OpenCodePluginAdd => "opencode_plugin_add" / "application.call",
    OpenCodePluginInstall => "opencode_plugin_install" / "application.call",
    OpenCodePluginList => "opencode_plugin_list" / "application.call",
    OpenCodePluginUninstall => "opencode_plugin_uninstall" / "application.call",
    OpenCodeProviderCatalog => "opencode_provider_catalog" / "application.call",
    OpenCodeProviderConnect => "opencode_provider_connect" / "application.call",
    OpenCodeProviderConnections => "opencode_provider_connections" / "application.call",
    OpenCodeProviderDisconnect => "opencode_provider_disconnect" / "application.call",
    OpenCodeProviderImport => "opencode_provider_import" / "application.call",
    OpenCodeProviderSetEnabled => "opencode_provider_set_enabled" / "application.call",
    PiCommandValidate => "pi_command_validate" / "application.call",
    PiConfiguration => "pi_configuration" / "application.call",
    PiCredentialsSave => "pi_credentials_save" / "application.call",
    PiPluginAdd => "pi_plugin_add" / "application.call",
    PiPluginRemove => "pi_plugin_remove" / "application.call",
    PiPlugins => "pi_plugins" / "application.call",
    PiRuntimeSave => "pi_runtime_save" / "application.call",
    PluginControlConfigureAgents => "plugin_control_configure_agents" / "plugin.write",
    PluginControlConfigureMcp => "plugin_control_configure_mcp" / "plugin.write",
    PluginControlContributions => "plugin_control_contributions" / "plugin.read",
    PluginControlPreviewImport => "plugin_control_preview_import" / "plugin.write",
    PluginControlRollback => "plugin_control_rollback" / "plugin.write",
    PluginControlUpdate => "plugin_control_update" / "plugin.write",
    PluginInstall => "plugin_install" / "plugin.write",
    PluginInvokeContribution => "plugin_invoke_contribution" / "plugin.surface",
    PluginMarketplaceIndex => "plugin_marketplace_index" / "plugin.read",
    PluginUninstall => "plugin_uninstall" / "plugin.write",
    PluginUpdate => "plugin_update" / "plugin.write",
    PluginWorkflowCatalog => "plugin_workflow_catalog" / "plugin.read",
    SetChatEventWebhooks => "set_chat_event_webhooks" / "application.call",
    SetChatMessageLanguage => "set_chat_message_language" / "application.call",
    WeixinCheckQrcode => "weixin_check_qrcode" / "application.call",
    WeixinGetQrcode => "weixin_get_qrcode" / "application.call",
    UpdateConfig => "update_config" / "application.call",
    GetSettingsFilePath => "get_settings_file_path" / "application.call",
    GetProfiles => "get_profiles" / "application.call",
    UpdateProfiles => "update_profiles" / "application.call",
    PlayNotificationSound => "play_notification_sound" / "application.call",
    CheckEditorAvailability => "check_editor_availability" / "application.call",
    EnhancePrompt => "enhance_prompt" / "application.call",
    ListPromptEnhancementModels => "list_prompt_enhancement_models" / "application.call",
    RefreshPromptEnhancementCatalogs => "refresh_prompt_enhancement_catalogs" / "application.call",
    GetClaudeSettings => "get_claude_settings" / "application.call",
    UpdateClaudeSettings => "update_claude_settings" / "application.call",
    GetClaudeSettingsPath => "get_claude_settings_path" / "application.call",
    ScanLocalSkills => "scan_local_skills" / "application.call",
    ReadLocalSkill => "read_local_skill" / "application.call",
    SearchSkillMarket => "search_skill_market" / "application.call",
    GetMarketSkillDetail => "get_market_skill_detail" / "application.call",
    InstallMarketSkill => "install_market_skill" / "application.call",
    SetSkillHosting => "set_skill_hosting" / "application.call",
    UninstallSkill => "uninstall_skill" / "application.call",
    ReadAgentSkill => "read_agent_skill" / "application.call",
    SaveAgentSkill => "save_agent_skill" / "application.call",
    DeleteAgentSkill => "delete_agent_skill" / "application.call",
    McpScanLocal => "mcp_scan_local" / "application.call",
    McpListMarketplaces => "mcp_list_marketplaces" / "application.call",
    McpSearchMarketplace => "mcp_search_marketplace" / "application.call",
    McpGetMarketplaceServerDetail => "mcp_get_marketplace_server_detail" / "application.call",
    McpInstallMarketplaceServer => "mcp_install_marketplace_server" / "application.call",
    McpUpsertLocalServer => "mcp_upsert_local_server" / "application.call",
    McpUninstallServer => "mcp_uninstall_server" / "application.call",
    ListInstructions => "list_instructions" / "application.call",
    ListOfficialInstructions => "list_official_instructions" / "application.call",
    CreateInstruction => "create_instruction" / "application.call",
    UpdateInstruction => "update_instruction" / "application.call",
    DeleteInstruction => "delete_instruction" / "application.call",
    InstallOfficialInstruction => "install_official_instruction" / "application.call",
    GetVersionControlSettings => "get_version_control_settings" / "application.call",
    UpdateVersionControlSettings => "update_version_control_settings" / "application.call",
    DetectGitVersion => "detect_git_version" / "application.call",
    TestGitPath => "test_git_path" / "application.call",
    GetGithubCliStatus => "get_github_cli_status" / "application.call",
    OpenGithubCliLogin => "open_github_cli_login" / "application.call",
    LogoutGithubCli => "logout_github_cli" / "application.call",
    InstallGithubCli => "install_github_cli" / "application.call",
    InstallVersionControlTools => "install_version_control_tools" / "application.call",
    GhCliSetup => "gh_cli_setup" / "application.call",
    ListChatChannels => "list_chat_channels" / "application.call",
    CreateChatChannel => "create_chat_channel" / "application.call",
    UpdateChatChannel => "update_chat_channel" / "application.call",
    DeleteChatChannel => "delete_chat_channel" / "application.call",
    ConnectChatChannel => "connect_chat_channel" / "application.call",
    DisconnectChatChannel => "disconnect_chat_channel" / "application.call",
    TestChatChannel => "test_chat_channel" / "application.call",
    GetChatChannelHasToken => "get_chat_channel_has_token" / "application.call",
    SaveChatChannelToken => "save_chat_channel_token" / "application.call",
    DeleteChatChannelToken => "delete_chat_channel_token" / "application.call",
    GetChatCommandPrefix => "get_chat_command_prefix" / "application.call",
    SetChatCommandPrefix => "set_chat_command_prefix" / "application.call",
    GetChatEventFilter => "get_chat_event_filter" / "application.call",
    SetChatEventFilter => "set_chat_event_filter" / "application.call",
    GetChatIncludePromptText => "get_chat_include_prompt_text" / "application.call",
    SetChatIncludePromptText => "set_chat_include_prompt_text" / "application.call",
    ListChatChannelStatuses => "list_chat_channel_statuses" / "application.call",
    ListChatChannelMessageLogs => "list_chat_channel_message_logs" / "application.call",
    GetLogSettings => "get_log_settings" / "application.call",
    SetLogSettings => "set_log_settings" / "application.call",
    GetRecentLogs => "get_recent_logs" / "application.call",
    GetLogsDir => "get_logs_dir" / "application.call",
    GetSystemProxySettings => "get_system_proxy_settings" / "application.call",
    UpdateSystemProxySettings => "update_system_proxy_settings" / "application.call",
    GetSystemRenderingSettings => "get_system_rendering_settings" / "application.call",
    UpdateSystemRenderingSettings => "update_system_rendering_settings" / "application.call",
    UploadImage => "upload_image" / "application.call",
    UploadImageForTask => "upload_image_for_task" / "application.call",
    UploadImageForWorkspace => "upload_image_for_workspace" / "application.call",
    WritePastedImageAsset => "write_pasted_image_asset" / "application.call",
    DeleteImage => "delete_image" / "application.call",
    GetTaskImages => "get_task_images" / "application.call",
    GetTaskImageMetadata => "get_task_image_metadata" / "application.call",
    GetWorkspaceImageMetadata => "get_workspace_image_metadata" / "application.call",
    GitCherryPick => "git_cherry_pick" / "application.call",
    GitCreateBranchAtCommit => "git_create_branch_at_commit" / "application.call",
    GitResetToCommit => "git_reset_to_commit" / "application.call",
    GitRevertCommit => "git_revert_commit" / "application.call",
    GetWorkspacePrComments => "get_workspace_pr_comments" / "application.call",
    InitRepoAtPath => "init_repo_at_path" / "application.call",
    GetReposBatch => "get_repos_batch" / "application.call",
    GetExecutionProcess => "get_execution_process" / "application.call",
    GetExecutionProcessRepoStates => "get_execution_process_repo_states" / "application.call",
    StopExecutionProcess => "stop_execution_process" / "application.call",
    StopWorkspaceExecution => "stop_workspace_execution" / "application.call",
    ResetSessionProcess => "reset_session_process" / "application.call",
    StartWorkspaceDevServer => "start_workspace_dev_server" / "application.call",
    GetFirstUserMessage => "get_first_user_message" / "application.call",
    RespondToApproval => "respond_to_approval" / "application.call",
    GetProjectUsageStatistics => "get_project_usage_statistics" / "application.call",
    ClearLocalAppData => "clear_local_app_data" / "application.call",
    CheckAppRelease => "check_app_release" / "application.call",
    GetWorktreeCleanupStatus => "get_worktree_cleanup_status" / "application.call",
    CrashReportsList => "crash_reports_list" / "application.call",
    CrashReportRead => "crash_report_read" / "application.call",
    CrashReportDelete => "crash_report_delete" / "application.call",
    WorkspaceContinueConflicts => "continue_conflicts_workspace" / "application.call",
    WorkspaceConflictFile => "get_workspace_conflict_file" / "application.call",
    WorkspaceWriteConflictResolution => "write_workspace_conflict_resolution" / "application.call",
    WorkspaceCreatePr => "create_workspace_pr" / "application.call",
    WorkspaceAttachPr => "attach_workspace_pr" / "application.call",
    WorkspaceCreateFromPr => "create_workspace_from_pr" / "application.call",
    WorkspaceRunSetupScript => "run_setup_script" / "application.call",
    WorkspaceRunCleanupScript => "run_cleanup_script" / "application.call",
    WorkspaceRunArchiveScript => "run_archive_script" / "application.call",
    WorkspaceShowStash => "show_workspace_stash" / "application.call",
    ConversationTimelinePage => "conversation_timeline_page" / "conversation.read",
    ConversationRebindSession => "conversation_rebind_session" / "conversation.write",
    ConversationTruncateToTurn => "conversation_truncate_to_turn" / "conversation.write",
    ConversationCheckpointPreview => "conversation_checkpoint_file_changes_preview" / "conversation.read",
    ConversationClose => "conversation_close" / "conversation.write",
    ConversationExport => "conversation_export" / "conversation.read",
    ConversationExportMarkdown => "conversation_export_markdown" / "conversation.read",
    ConversationExportHtml => "conversation_export_html" / "conversation.read",
    ConversationSearch => "conversation_search" / "conversation.read",
    ConversationImport => "conversation_import" / "conversation.write",
    ConversationFork => "conversation_fork" / "conversation.write",
    AgentScanLocalHistory => "agent_scan_local_history" / "application.call",
}

#[async_trait]
pub trait ApplicationDomainPort: Send + Sync {
    async fn execute(
        &self,
        principal: &Principal,
        command: DomainCommand,
        args: serde_json::Value,
    ) -> Result<serde_json::Value, ApplicationError>;
}

pub(crate) struct UnavailableApplicationDomains;

#[async_trait]
impl ApplicationDomainPort for UnavailableApplicationDomains {
    async fn execute(
        &self,
        _principal: &Principal,
        command: DomainCommand,
        _args: serde_json::Value,
    ) -> Result<serde_json::Value, ApplicationError> {
        Err(ApplicationError::capability_unavailable(format!(
            "{} is not configured",
            command.as_str()
        )))
    }
}

pub(crate) fn unavailable_domains() -> Arc<dyn ApplicationDomainPort> {
    Arc::new(UnavailableApplicationDomains)
}

#[cfg(test)]
mod tests {
    use super::DomainCommand;

    #[test]
    fn domain_command_names_are_unique() {
        let mut names = DomainCommand::ALL
            .iter()
            .map(|command| command.as_str())
            .collect::<Vec<_>>();
        names.sort_unstable();
        let before = names.len();
        names.dedup();
        assert_eq!(names.len(), before);
    }

    #[test]
    fn capability_scopes_include_registered_domain_scopes() {
        let scopes = DomainCommand::capability_scopes();
        for command in DomainCommand::ALL {
            assert!(
                scopes.contains(&command.required_scope()),
                "{} scope {} missing from capabilities",
                command.as_str(),
                command.required_scope()
            );
        }
        assert!(!scopes.contains(&"workspace.write"));
        assert!(!scopes.contains(&"desktop.tauri"));
    }
}
