[package]
name = "db"
version = "0.1.8"
edition = "2024"

[dependencies]
utils = { path = "../utils" }
executors = { path = "../executors" }
agents = { path = "../agents" }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "tls-rustls-aws-lc-rs", "sqlite", "sqlite-preupdate-hook", "chrono", "uuid"] }
chrono = { workspace = true }
uuid = { workspace = true }
ts-rs = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

